2022-01-09 17:21:25,250 INFO    MainThread:13050 [wandb_setup.py:_flush():71] setting env: {}
2022-01-09 17:21:25,251 INFO    MainThread:13050 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-09 17:21:25,251 INFO    MainThread:13050 [wandb_init.py:_log_setup():371] Logging user logs to /content/tbcnn/wandb/run-20220109_172125-2al0xcja/logs/debug.log
2022-01-09 17:21:25,251 INFO    MainThread:13050 [wandb_init.py:_log_setup():372] Logging internal logs to /content/tbcnn/wandb/run-20220109_172125-2al0xcja/logs/debug-internal.log
2022-01-09 17:21:25,251 INFO    MainThread:13050 [wandb_init.py:init():404] calling init triggers
2022-01-09 17:21:25,251 INFO    MainThread:13050 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-09 17:21:25,251 INFO    MainThread:13050 [wandb_init.py:init():460] starting backend
2022-01-09 17:21:25,251 INFO    MainThread:13050 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-09 17:21:25,267 INFO    MainThread:13050 [backend.py:ensure_launched():216] starting backend process...
2022-01-09 17:21:25,281 INFO    MainThread:13050 [backend.py:ensure_launched():222] started backend process with pid: 13063
2022-01-09 17:21:25,294 INFO    MainThread:13050 [wandb_init.py:init():469] backend started and connected
2022-01-09 17:21:25,300 INFO    MainThread:13050 [wandb_init.py:init():533] updated telemetry
2022-01-09 17:21:25,378 INFO    MainThread:13050 [wandb_init.py:init():563] communicating current version
2022-01-09 17:21:26,495 INFO    MainThread:13050 [wandb_init.py:init():568] got version response 
2022-01-09 17:21:26,495 INFO    MainThread:13050 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-09 17:21:26,729 INFO    MainThread:13050 [wandb_init.py:init():606] starting run threads in backend
2022-01-09 17:21:29,572 INFO    MainThread:13050 [wandb_run.py:_console_start():1810] atexit reg
2022-01-09 17:21:29,572 INFO    MainThread:13050 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-09 17:21:29,573 INFO    MainThread:13050 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-09 17:21:29,582 INFO    MainThread:13050 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-09 17:21:29,582 INFO    MainThread:13050 [wandb_init.py:init():633] run started, returning control to user process
2022-01-09 17:21:48,883 INFO    MainThread:13050 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 255
2022-01-09 17:21:48,885 INFO    MainThread:13050 [wandb_run.py:_restore():1752] restore
2022-01-09 17:21:51,270 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 686
  total_bytes: 686
}

2022-01-09 17:21:51,497 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 686
  total_bytes: 686
}

2022-01-09 17:21:51,819 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 686
  total_bytes: 8286
}

2022-01-09 17:21:51,921 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 686
  total_bytes: 14288
}

2022-01-09 17:21:52,024 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 686
  total_bytes: 14288
}

2022-01-09 17:21:52,126 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}

2022-01-09 17:21:52,229 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}

2022-01-09 17:21:52,331 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}

2022-01-09 17:21:52,434 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}

2022-01-09 17:21:52,536 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}

2022-01-09 17:21:52,958 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}

2022-01-09 17:21:53,437 INFO    MainThread:13050 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14288
  total_bytes: 14288
}
local_info {
}

2022-01-09 17:21:55,128 INFO    MainThread:13050 [wandb_run.py:_append_files():2180] logging synced files
